version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Geetha3230
      MYSQL_DATABASE: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  foodorder-app:
    build: .
    container_name: foodorder-app
    ports:
      - "8081:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=user
      - DB_USER=root
      - DB_PASSWORD=Geetha3230
      - SERVER_PORT=8081

volumes:
  mysql_data:
